version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, flutter]
    open-pull-requests-limit: 5
